export const LEBANON_REGIONS = [
  { value: 'Beirut', label: 'Beirut' },
  { value: 'Achrafieh', label: 'Achrafieh' },
  { value: 'Hamra', label: 'Hamra' },
  { value: 'Mar Mikhael', label: 'Mar Mikhael' },
  { value: 'Gemmayzeh', label: 'Gemmayzeh' },
  { value: 'Downtown Beirut', label: 'Downtown Beirut (BCD)' },
  { value: 'Verdun', label: 'Verdun' },
  { value: 'Raouche', label: 'Raouche' },
  { value: 'Zaitunay Bay', label: 'Zaitunay Bay' },
  { value: 'Dbayeh', label: 'Dbayeh' },
  { value: 'Jounieh', label: 'Jounieh' },
  { value: 'Byblos', label: 'Byblos (Jbeil)' },
  { value: 'Tripoli', label: 'Tripoli' },
  { value: 'Saida', label: 'Saida (Sidon)' },
  { value: 'Tyre', label: 'Tyre (Sour)' },
  { value: 'Batroun', label: 'Batroun' },
  { value: 'Zahle', label: 'Zahle' },
  { value: 'Baalbek', label: 'Baalbek' },
  { value: 'Bcharre', label: 'Bcharre' },
  { value: 'Faraya', label: 'Faraya' },
  { value: 'Broumana', label: 'Broumana' },
  { value: 'Aley', label: 'Aley' },
  { value: 'Chouf', label: 'Chouf' },
  { value: 'Nabatieh', label: 'Nabatieh' },
  { value: 'Other', label: 'Other' },
];
